import FWCore.ParameterSet.Config as cms

vnanalyzer = cms.EDAnalyzer("VNAnalyzer",
                            vertexTag_=cms.InputTag("hiSelectedVertex"),
                            centralityTag_=cms.InputTag("hiCentrality"),
                            inputPlanesTag_ = cms.InputTag("hiEvtPlaneFlat"),
                            centralityBinTag_ = cms.InputTag("centralityBin","HFtowers"),
                            bTag_ = cms.InputTag("mcEvtPlane","b","VNANAL"),
                            RPTag_ = cms.InputTag("mcEvtPlane","rp","VNANAL"),
                            pfTag = cms.untracked.InputTag("particleFlowTmp"),
                            centralityVariable = cms.string("HFtowers"),
                            nonDefaultGlauberModel = cms.string(""),
                            FlatOrder_ = cms.untracked.int32(9),
                            NumFlatBins_ = cms.untracked.int32(40),
                            flatnvtxbins = cms.int32(10),
                            flatminvtx = cms.double(-25.0),
                            flatdelvtx = cms.double(5.0),
                            BinLabel = cms.InputTag("Noff"),
                            trackTag_=cms.InputTag("hiGeneralAndPixelTracks"),
                            offsetFile = cms.string("offset_pPb2016_MB_1_285832.root"),
                            useNtrk = cms.untracked.bool(False),
                            genMC = cms.untracked.bool(False),
                            effTable_ = cms.string('NULL'),
                            nvtx_ = cms.untracked.int32(100),
                            minvz_ = cms.untracked.double(-15.),
                            maxvz_ = cms.untracked.double(15.),
                            dzdzerror_ = cms.untracked.double(3.0),
                            d0d0error_ = cms.untracked.double(3.0),
                            pterror_ = cms.untracked.double(0.1),
                            Recenter = cms.untracked.bool(True),
                            EPLevel = cms.untracked.int32(2),
                            dzdzerror_pix_ = cms.untracked.double(8.0),
                            chi2_ = cms.untracked.double(12.)
 )
